apiVersion: v1
kind: ConfigMap
metadata:
  name: mindquest-config
  namespace: mindquest
data:
  PORT: "3001"
  AI_SERVICE_URL: "http://mindquest-ai:5001"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  FRONTEND_URL: "https://mindquest.example.com"
