apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mindquest

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - frontend.yaml
  - backend.yaml
  - ai-service.yaml
  - ingress.yaml

commonLabels:
  project: mindquest
