apiVersion: v1
kind: Secret
metadata:
  name: mindquest-secrets
  namespace: mindquest
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://manikantachapala1573:AHkKzoxgKaHmkxie@cluster0.drbsc5k.mongodb.net/mindquest"
  JWT_SECRET: "mindquest_secret_key_2025_brainstorming_ai"
  GEMINI_API_KEY: "AIzaSyBDsHubIKHikIth-VKKaytcSClL9sO7u6A"
  EMAIL_USER: "harshaithireddy446@gmail.com"
  EMAIL_PASSWORD: "wajnomibsjervlpd"
