apiVersion: v1
kind: Secret
metadata:
  name: mindquest-secrets
  namespace: mindquest
type: Opaque
stringData:
  MONGO_URI: "REPLACE_WITH_YOUR_MONGO_URI"
  JWT_SECRET: "REPLACE_WITH_YOUR_JWT_SECRET"
  GEMINI_API_KEY: "REPLACE_WITH_YOUR_GEMINI_KEY"
  EMAIL_USER: "REPLACE_WITH_YOUR_EMAIL"
  EMAIL_PASSWORD: "REPLACE_WITH_YOUR_EMAIL_PASSWORD"
