apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mindquest-staging

resources:
  - ../../base

namePrefix: staging-

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Ingress
      name: mindquest-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: staging.mindquest.example.com

  - target:
      kind: ConfigMap
      name: mindquest-config
    patch: |
      - op: replace
        path: /data/FRONTEND_URL
        value: https://staging.mindquest.example.com
